before_script:
  - echo "starting build uam-admin-fe...."
  - echo $CI_COMMIT_TAG

stages:
  - build_docker_image

build_docker_image-job:
  stage: build_docker_image
  image: wuyuw/dind:node16
  script:
    - bash deploy/build.sh -v $CI_COMMIT_TAG -u $DOCKER_USER -p $DOCKER_PASSWORD
  only:
    - /v\d+\.\d+\.\d+$/
  tags:
    - mua_docker_runner
